#!/bin/bash

# Read the repo name passed as an argument
repo_name=$1

# Check if a repo name was provided
if [ "$repo_name" == "" ]; then
  echo "Please provide a repository name."
  exit 1
fi

# Create a directory with the given repo name
mkdir "/Users/cansin/Scripts/$repo_name" || { echo "Failed to create directory '$repo_name'. It may already exist."; exit 1; }


# Change into the new directory
cd "/Users/cansin/Scripts/$repo_name" || { echo "Failed to change directory to '$repo_name'"; exit 1; }

# Initialize an empty git repository
git init -b main
git add .
git commit --allow-empty -m "first commit"

# Create the GitHub repository, add it as remote, then push
gh repo create "$repo_name" --private --source=. --remote=origin --push

# Open the directory in VS Code
code .